<a href="https://colab.research.google.com/github/MareevaMI/PDA_SOL/blob/main/02_Linear_algebra(%D0%9C%D0%B0%D1%80%D0%B5%D0%B5%D0%B2%D0%B0_%D0%9C_%D0%98_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Линейная алгебра с Numpy

С помощью [Sympy](http://www.sympy.org/en/index.html) можно выполнять символьную линейную алгебру, но для числовых вычислений [Numpy](http://www.numpy.org/) является высокопроизводительная библиотека, которую следует использовать при решении математических и инженерныхзадач.

Описание:

> NumPy — это фундаментальный пакет для научных вычислений на Python. Он содержит, среди прочего: [...]
 линейную алгебру, преобразование Фурье и теорию вероятностей.

В этом разделе научимся, как:

- работать с матрицами;
- решать матричные уравнения;
- рассчитывать обратную матрицу и определители.

## Работа с матрицами

Создать матрицу с помощью Numpy несложно. В качестве примера рассмотрим следующее:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


Сначала, как и в Sympy, нам нужно импортировать Numpy:

In [27]:
import numpy as np

Теперь можем определить $A$:

In [28]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [29]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [30]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [31]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

Можно получить как следствие:

- $5A$ (или любое другое скалярное число, кратное $A$);
- $A ^ 3$ (или любой другой показатель $A$);
- $A + B$;
- $A - B$;
- $AB$

In [32]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [33]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [34]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [35]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [36]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

---

**УПРАЖНЕНИЕ 1** Решить $A ^ 2 – 2 A + 3$ с помощью:

$$A =
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$

---

## Решение матричных уравнений

Можно использовать Numpy для (эффективного) решения больших систем уравнений вида:

$$Ax=b$$

Проиллюстрируем это:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [37]:
# Упражнение 1
A = np.matrix([[1, -1],
               [2, 1]])
A

matrix([[ 1, -1],
        [ 2,  1]])

In [38]:
A ** 2 - 2 * A + 3

matrix([[0, 3],
        [3, 0]])

In [39]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Мы используем команду `linalg.solve`:

In [40]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Проверим результат:

In [41]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

---
**УПРАЖНЕНИЕ 2** Найти решение матричного уравнения $Bx=b$ (используя $B$).

---

## Обратные матрицы и определители

Найдем обратную матрицу:

In [42]:
# Упражнение 2
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
b = np.matrix([[-1], [2], [1]])
x = np.linalg.solve(B, b)
x

matrix([[-0.25892857],
        [ 0.40178571],
        [ 0.28571429]])

In [43]:
# Проверка решения
B*x
# Решение верное

matrix([[-1.],
        [ 2.],
        [ 1.]])

In [44]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

Проверка $A^{-1}A=\mathbb{1}$:

In [45]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -4.71844785e-16],
        [ 1.38777878e-16,  1.00000000e+00, -2.63677968e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

Казалось бы, что матрица не единичная, однако по главной  `1` , а на всех остальных позициях **очень** маленькие числа (однако для компьютера это `0`).

Вычислим детерминант:

In [46]:
np.linalg.det(A)

-129.00000000000009

---

**УПРАЖНЕНИЕ 2** Вычислите обратную матрицу и определитель $B$ (ранее уже находили).

---

In [47]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
Binv = np.linalg.inv(B)
Binv

matrix([[ 6.25000000e-02, -1.84523810e-01,  1.72619048e-01],
        [-6.25000000e-02,  1.36904762e-01,  6.54761905e-02],
        [-1.09511795e-17,  2.38095238e-01, -1.90476190e-01]])

In [48]:
np.linalg.det(B)

-336.0