<a href="https://colab.research.google.com/github/MareevaMI/PDA_SOL/blob/main/Numpy(%D0%9C%D0%B0%D1%80%D0%B5%D0%B5%D0%B2%D0%B0_%D0%9C_%D0%98_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
np.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full(7,7)


array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
arr = np.random.random_sample(10)
arr

array([0.72033795, 0.06880954, 0.50053567, 0.14525418, 0.51651395,
       0.53178772, 0.84864733, 0.06723814, 0.90554313, 0.87754161])

In [ ]:
arr[::-1]

array([0.87754161, 0.90554313, 0.06723814, 0.84864733, 0.53178772,
       0.51651395, 0.14525418, 0.50053567, 0.06880954, 0.72033795])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
b = np.arange(0, 9)
b = b.reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
a = np.full([4,4], 7)
a -= np.diag([6, 5, 4, 3])
a

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
b = np.zeros((5, 5))
b += np.arange(0, 5)
b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [5]:
d=np.random.random((10,10))
print('Исходная матрица: \n',d)
e=d.mean(axis=1, keepdims=True)
print('Среднее по строкам: \n',e)
d -=e
print('Итог: \n',d)

Исходная матрица: 
 [[0.53415783 0.24358875 0.06219111 0.6470386  0.00806383 0.2057638
  0.43473933 0.21917282 0.71050105 0.39974596]
 [0.74967883 0.29620976 0.72192716 0.17393893 0.55534448 0.57440929
  0.4398412  0.73126481 0.95937063 0.68950467]
 [0.93916917 0.20588715 0.55946621 0.51171181 0.74031767 0.31940658
  0.80821997 0.82985785 0.72751955 0.59635496]
 [0.56805267 0.54255596 0.59496472 0.46996834 0.86757515 0.63659245
  0.80601191 0.92890301 0.61740026 0.95133016]
 [0.02285463 0.93801979 0.08994726 0.35425231 0.34696818 0.63730383
  0.2952128  0.02112454 0.09987502 0.11254071]
 [0.30019137 0.87734296 0.98710304 0.83823493 0.5156146  0.42413577
  0.83758945 0.26134662 0.98519088 0.32874746]
 [0.30877298 0.72225748 0.61113546 0.8280372  0.02866624 0.18652231
  0.12503138 0.91737928 0.89856409 0.30176288]
 [0.02060907 0.77701088 0.07928162 0.94586001 0.73997233 0.87716371
  0.74893764 0.19626733 0.03615431 0.70369796]
 [0.76868394 0.77911034 0.34023882 0.27818272 0.23346912 0.22

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [7]:
d=np.random.random((10,10))
print('Исходная матрица: \n',d)
e=np.median(d,axis=0, keepdims=True)
print('Медиана по столбцам: \n',e)
d -=e
print('Итог: \n',d)

Исходная матрица: 
 [[0.97533091 0.68357273 0.0685994  0.21304833 0.07751438 0.31600553
  0.57540581 0.72193798 0.56462786 0.21459498]
 [0.03924649 0.75048934 0.66728702 0.46946316 0.70055719 0.60711197
  0.99625405 0.86235103 0.23217371 0.49903592]
 [0.80615284 0.20265875 0.29672402 0.65921114 0.14820959 0.79403841
  0.58894573 0.59347655 0.47524545 0.91831342]
 [0.44691731 0.8067923  0.78953798 0.23206085 0.14061853 0.49768825
  0.67720286 0.23841994 0.99770174 0.43546247]
 [0.92574875 0.33422484 0.1092523  0.67923826 0.52927113 0.08559589
  0.03044566 0.88963304 0.76611276 0.53630889]
 [0.86493754 0.16379346 0.62837238 0.45776678 0.16302026 0.1173519
  0.83073638 0.87720552 0.95176195 0.65681772]
 [0.69961593 0.19650104 0.05443426 0.21857811 0.97415173 0.21159784
  0.0704653  0.50771066 0.10052841 0.17173175]
 [0.65374431 0.10084429 0.74815674 0.6541045  0.25728499 0.81436014
  0.70355829 0.35925594 0.89710885 0.99850968]
 [0.30581769 0.54708502 0.81710452 0.86014457 0.99394524 0.77

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [8]:
d=np.random.random((5,5))
print('Исходная матрица: \n',d)
e=d.max(axis=1, keepdims=True)
f=d.min(axis=1,keepdims=True)
print('Итог: \n',np.hstack((d,e,f)))

Исходная матрица: 
 [[0.17450444 0.65420257 0.1811126  0.56459323 0.43823396]
 [0.62663343 0.82970301 0.12380358 0.92247895 0.66887672]
 [0.7535307  0.81294398 0.58777445 0.56838625 0.95285478]
 [0.8061004  0.75281731 0.9887551  0.84072342 0.531114  ]
 [0.94005714 0.32593693 0.5251008  0.62834634 0.32374363]]
Итог: 
 [[0.17450444 0.65420257 0.1811126  0.56459323 0.43823396 0.65420257
  0.17450444]
 [0.62663343 0.82970301 0.12380358 0.92247895 0.66887672 0.92247895
  0.12380358]
 [0.7535307  0.81294398 0.58777445 0.56838625 0.95285478 0.95285478
  0.56838625]
 [0.8061004  0.75281731 0.9887551  0.84072342 0.531114   0.9887551
  0.531114  ]
 [0.94005714 0.32593693 0.5251008  0.62834634 0.32374363 0.94005714
  0.32374363]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [23]:
z=np.arange(1,52)
print(z)
a=z[z % 2 != 0]
a=a[0:25].reshape(5,5)
np.random.shuffle(a)
print('Первая матрица: \n',a)
b=z[z % 2 == 0].reshape(5,5)
np.random.shuffle(b)
print('Вторая матрица: \n',b)
c=a.dot(b)
print('Произведение матриц: \n',c)
arr = np.array([[410, 460, 510, 560, 610],
                [1510, 1660, 1810, 1960, 2110],
                [4810, 5260, 5710, 6160, 6610],
                [3710, 4060, 4410, 4760, 5110],
                [2160, 2860, 3110, 3360, 3610]])

inverse_array = np.linalg.inv(arr)
print('Обратная матрица: \n',inverse_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]
Первая матрица: 
 [[41 43 45 47 49]
 [ 1  3  5  7  9]
 [31 33 35 37 39]
 [11 13 15 17 19]
 [21 23 25 27 29]]
Вторая матрица: 
 [[22 24 26 28 30]
 [12 14 16 18 20]
 [ 2  4  6  8 10]
 [42 44 46 48 50]
 [32 34 36 38 40]]
Произведение матриц: 
 [[5050 5500 5950 6400 6850]
 [ 650  700  750  800  850]
 [3950 4300 4650 5000 5350]
 [1750 1900 2050 2200 2350]
 [2850 3100 3350 3600 3850]]
Обратная матрица: 
 [[-1.66320166e-03  4.15800416e-03 -8.31600832e-04  1.24740125e-03
  -2.22222222e-03]
 [ 3.57341279e+12 -4.39804651e+12  1.92414535e+12 -1.09951163e+12
   3.54204587e-04]
 [-5.49755814e+12  6.59706977e+12 -3.29853488e+12  2.19902326e+12
   4.79004110e-03]
 [ 2.74877907e+11 -0.00000000e+00  8.24633721e+11 -1.09951163e+12
  -1.75380707e-03]
 [ 1.64926744e+12 -2.19902326e+12  5.49755814e+11 -0.00000000e+00
  -1.16821639e-03]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [15]:
k = np.zeros((8,8),dtype=int)
k[1::2,::2] = 1
k[::2,1::2] = 1
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
